# Generated by Django 4.2.3 on 2023-07-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='deadline_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='deadline_time',
            field=models.TimeField(null=True),
        ),
    ]
