# Generated by Django 4.2.3 on 2023-07-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_group_deadline_date_alter_group_deadline_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='group',
            name='deadline_time',
        ),
        migrations.AddField(
            model_name='group',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
